#!/bin/sh -e
LIBVA_DIR="$HOME/.local/share/linutil/libva"
MPV_CONF="$HOME/.config/mpv/mpv.conf"
installDeps() {
    Package_installer_ base-devel dkms ninja meson git
    installed_kernels=$("$PACKAGER" -Q | grep -E '^linux(| |-rt|-rt-lts|-hardened|-zen|-lts)[^-headers]' | cut -d ' ' -f 1)
    for kernel in $installed_kernels; do
        header="${kernel}-headers"
        say "Installing headers for $kernel..."
        Package_installer_ "$header"
    done
}
checkNvidiaHardware() {
    # Refer https://nouveau.freedesktop.org/CodeNames.html for model code names
    model=$(lspci -k | grep -A 2 -E "(VGA|3D)" | grep NVIDIA | sed 's/.*Corporation //;s/ .*//' | cut -c 1-2)
    case "$model" in
        GM | GP | GV) return 1 ;;
        TU | GA | AD) return 0 ;;
        *) say "Unsupported hardware." && exit 1 ;;
    esac
}
checkIntelHardware() {
    model=$(grep "model name" /proc/cpuinfo | head -n 1 | cut -d ':' -f 2 | cut -c 2-3)
    [ "$model" -ge 11 ]
}

setKernelParam() {
    PARAMETER="$1"
    if grep -q "$PARAMETER" /etc/default/grub; then
        say "NVIDIA modesetting is already enabled in GRUB."
    else
        my-superuser sed -i "/^GRUB_CMDLINE_LINUX_DEFAULT=/ s/\"$/ $PARAMETER\"/" /etc/default/grub
        say "Added $PARAMETER to /etc/default/grub."
        my-superuser grub-mkconfig -o /boot/grub/grub.cfg
    fi
}
setupHardwareAcceleration() {
    if ! command_exists grub-mkconfig; then
        say "Currently hardware acceleration is only available with GRUB."
        return
    fi
    Package_installer_ libva-nvidia-driver
    mkdir -p "$HOME/.local/share/linutil"
    if [ -d "$LIBVA_DIR" ]; then
        rm -rf "$LIBVA_DIR"
    fi
    say "Cloning libva from https://github.com/intel/libva in ${LIBVA_DIR}"
    git clone --branch=v2.22-branch --depth=1 https://github.com/intel/libva "$LIBVA_DIR"
    mkdir -p "$LIBVA_DIR/build"
    cd "$LIBVA_DIR/build" && arch-meson .. -Dwith_legacy=nvctrl && ninja
    my-superuser ninja install
    my-superuser sed -i '/^MOZ_DISABLE_RDD_SANDBOX/d' "/etc/environment"
    my-superuser sed -i '/^LIBVA_DRIVER_NAME/d' "/etc/environment"
    printf "LIBVA_DRIVER_NAME=nvidia\nMOZ_DISABLE_RDD_SANDBOX=1" | my-superuser tee -a /etc/environment >/dev/null
    say "Hardware Acceleration setup completed successfully."
    if prompt "enable Hardware Acceleration in MPV player" 'Y'; then
        mkdir -p "$HOME/.config/mpv"
        if [ -f "$MPV_CONF" ]; then
            sed -i '/^hwdec/d' "$MPV_CONF"
        fi
        printf "hwdec=auto" | tee -a "$MPV_CONF" >/dev/null
        say "MPV Hardware Acceleration enabled successfully."
    fi
}
installDriver() {
    # Refer https://wiki.archlinux.org/title/NVIDIA for open-dkms or dkms driver selection
    if checkNvidiaHardware && prompt "install nvidia's open source drivers" 'Y'; then
        say "Installing nvidia open source driver..."
        installDeps
        Package_installer_ nvidia-open-dkms nvidia-utils
    else
        say "Installing nvidia proprietary driver..."
        installDeps
        Package_installer_ nvidia-dkms nvidia-utils
    fi
    if checkIntelHardware; then
        setKernelParam "ibt=off"
    fi
    # Refer https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend
    setKernelParam "nvidia.NVreg_PreserveVideoMemoryAllocations=1"
    my-superuser systemctl enable nvidia-suspend.service nvidia-hibernate.service nvidia-resume.service
    say "Driver installed successfully."
    if prompt "setup Hardware Acceleration" 'Y'; then
        setupHardwareAcceleration
    fi
    say "Please reboot your system for the changes to take effect."
}
installDriver
