#!/bin/sh
Distro_Specific_temp_path="$(cd "$(dirname "$0")"; pwd)"
Distro_Specific_path="/usr/share/my_stuff/Distro_Specific"
my-superuser rm -rdf "${Distro_Specific_path}"
my-superuser chown -R root:root "${Distro_Specific_temp_path}"

if [ -f "$Distro_Specific_path/info" ];then
	. "$Distro_Specific_path/info"
else
	distro_name="${1:-}"
	PACKAGER="${2:-}"
	if [ -z "${distro_name}" ];then
		echo "checking your distro."
		. "/usr/share/my_stuff/os-release"
		echo "Using ${distro_name}"
	fi

	if ! . "${Distro_Specific_temp_path}/${distro_name}/info" ;then
		echo "failed to source : ${Distro_Specific_temp_path}/${distro_name}/info"
		if ! . "${Distro_Specific_temp_path}/arch/info" ;then
			echo "failed to source : ${Distro_Specific_temp_path}/arch/info"
		fi
	fi
fi
echo "creating Package-managers library file."
cat "${Distro_Specific_temp_path}"/disto_package_manager/common | my-superuser tee "${Distro_Specific_temp_path}/${distro_name}/Package-manager" >/dev/null 2>&1
if [ "$PACKAGER" = "yay" ]; then
    PACKAGER="pacman"
elif [ "$PACKAGER" = "paru" ]; then
    PACKAGER="pacman"
fi
cat "${Distro_Specific_temp_path}"/disto_package_manager/${PACKAGER}.sh | my-superuser tee -a "${Distro_Specific_temp_path}/${distro_name}/Package-manager" >/dev/null 2>&1
my-superuser cp -r "${Distro_Specific_temp_path}/${distro_name}" "$Distro_Specific_path"

