#!/bin/sh -e
app_name="code"

say "Add Repo..." 1
my-superuser rpm --import https://packages.microsoft.com/keys/microsoft.asc
printf "%b\n" '[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc' | my-superuser tee /etc/yum.repos.d/vscode.repo > /dev/null

say "Installing ${app_name}..." 1
Package_installer_ ${app_name}
